# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: git config
        env:
          SUPER_SECRET: ${{ secrets.EMAIL}}
        run: |
          git config --global user.email "SUPER_SECRET"
          git config --global user.name "quanghoang72"
      - uses: actions/checkout@v3
      - name: Add file to corresponding file
        run: |
          test=$(ls -Ileetcode -Igeekforgeeks -Ireadme.md)
          if [[ -d "$test" ]];
          then 
            rm -r leetcode/$test
            mv $test leetcode/
            git rm -r $test 
            git add leetcode/$test
            git commit -m "add to lc"
            git push -u origin main
          else 
            mv $test geekforgeeks/
            git rm $test 
            git add geekforgeeks/$test
            git commit -m "add to gfg"
            git push -u origin main
          fi
